version: "2"
engines:
  eslint:
    enabled: true
ratings:
  paths:
    [
      "webpack-subresource-integrity/index.ts",
      "webpack-subresource-integrity/plugin.ts",
      "webpack-subresource-integrity/util.ts",
      "webpack-subresource-integrity/reporter.ts",
      "webpack-subresource-integrity/types.ts",
      "webpack-subresource-integrity/scc.ts",
    ]
exclude_patterns:
  - "node_modules/"
  - "examples/"
  - "smoke-test/"
  - ".git/"
  - ".github/"
  - ".yarn/"
  - ".nyc_merged/"
  - ".nyc_output/"
  - "**/coverage/"
  - "**/dist/"
  - "**/temp/"
  - "**/*.js"
  - "**/*.cjs"
  - "**/*.d.ts"
  - "**/*.map"
  - "**/*.tgz"
  - "**/.log"
  - "**/.eslintrc.js"
