version: "2"
engines:
  eslint:
    enabled: true
ratings:
  paths: ["webpack-subresource-integrity/src/*.ts"]
exclude_patterns:
  - "node_modules/"
  - "examples/"
  - "smoke-test/"
  - ".git/"
  - ".github/"
  - ".yarn/"
  - ".nyc_merged/"
  - ".nyc_output/"
  - "**/coverage/"
  - "**/dist/"
  - "**/temp/"
  - "**/*.js"
  - "**/*.cjs"
  - "**/*.d.ts"
  - "**/*.map"
  - "**/*.tgz"
  - "**/.log"
  - "**/.eslintrc.js"
