packageExtensions:
  fastify-static@*:
    peerDependencies:
      fastify: "*"
  html-webpack-include-assets-plugin@*:
    peerDependencies:
      html-webpack-plugin: "*"
  webpack@*:
    dependencies:
      "@types/json-schema": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs

nodeLinker: node-modules
